# Generated by Django 5.1.1 on 2024-10-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('region_code', models.CharField(max_length=10)),
                ('province_code', models.CharField(max_length=10)),
                ('city_municipality_code', models.CharField(max_length=10)),
                ('barangay_code', models.CharField(max_length=10)),
                ('house_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('treasurer', 'Treasurer'), ('staff', 'Staff'), ('applicant', 'Applicant')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('valid_id', models.FileField(upload_to='valid_ids/')),
                ('documents', models.FileField(upload_to='documents/')),
                ('terms_conditions', models.BooleanField(default=False)),
                ('data_privacy', models.BooleanField(default=False)),
            ],
        ),
    ]
